version: "1.0"

services:
  db:
    image: mysql:8.0
    env_file: ./.env
    restart: always
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
        - dbVol:/var/lib/mysql
  api:
    depends_on:
      - db
    build: ./test-app
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:$DB_DOCKER_PORT/$DB_NAME?useSSL=false",
          "spring.datasource.username" : "$DB_USER",
          "spring.datasource.password" : "$DB_ROOT_PASSWORD"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  dbVol: